# Generated by Django 4.2.11 on 2024-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customerbusiness_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbusiness',
            name='building_floor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerbusiness',
            name='building_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
